/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.onesoftnet.spark

import kotlinx.serialization.json.Json
import org.onesoftnet.spark.utils.Config
import java.io.File
import kotlinx.serialization.decodeFromString
import net.dv8tion.jda.api.JDABuilder
import org.onesoftnet.spark.events.MessageEventListener

fun main() {
    val token = System.getenv("TOKEN");

    if (token == null) {
        println("A token must be set in the env.");
        return;
    }

    val prefix = System.getenv("SPARK_PREFIX") ?: "."
    val file = File("$prefix/config/config.json")
    val config = Json.decodeFromString<Map<String, Config>>(file.readText())
    println(config.toString());

    val jdaBuilder = JDABuilder.createDefault(token);
    val jda = jdaBuilder.build();
    jda.addEventListener(MessageEventListener())
}
